### ISSUE TITLE
Noms ambigües "Damage"

### ISSUE THREAD

**Issue by GlennPlou** [RaphaelPage0110/mini-hearthStone#1]
Les implémentations de Target.takeDamage(int damagePoints) et de l'attribut Minion.damagePoints ont des noms un peu ambigüe. Dans l'idée il faudrait voir pour renommer la méthode "blesser" (hurt) et "points d'attaque" (attackPoints) pour l'attribut. 

En bref : trouver de meilleurs noms.

**Comment by henribouvet** [comment]
damageDealt peut être une bonne alternative sinon je pense. De même, damageTaken pour la victime

**Comment by henribouvet** [comment]
J'ai modifié Target.takeDamage(int damagePoints) -> Target.takeDamage(int damageTaken).
