### ISSUE TITLE
Attributs des classes de comportements

### ISSUE THREAD

**Issue by GlennPlou** [RaphaelPage0110/mini-hearthStone#10]
Les classes de comportements sont pour l'instant implémentées avec un attribut `private Minion myMinion;` ou `private Spell mySpell;` selon le fait qu'elles soient spécifiques à un Minion ou à un Spell.
Cet attribut pourrait être généralisé à une Card pour le moment, et caster si besoin la Card en Minion ou Spell.
De plus, selon l'issue #9 , on souhaiterait peut-être généraliser cette carte pour référencer des héros.

**Comment by RaphaelPage0110** [comment]
Si tu veux! Je pense que les deux fonctionnent, mais autant être aussi général que possible?
