### ISSUE TITLE
Classes serviteurs temporaires

### ISSUE THREAD

**Issue by GlennPlou** [RaphaelPage0110/mini-hearthStone#2]
Les sous-classes serviteurs (Minion) : "Chevaucheur de Loup", "Sanglier", Soldat du compté de l'or", "chef de raid", etc. sont présentes pour présenter des cas concrets de l'application et devront sans doute être supprimées pour être remplacées par une classe générale "ConcreteMinion".

**Comment by henribouvet** [comment]
Ce sont des stubs (ou mocks je sais plus) ?

**Comment by GlennPlou** [comment]
Ca peut en effet servir de mock, à voir ;)
Mais l'idée de base c'était surtout de comprendre le fonctionnement du pattern strategy !
