### ISSUE TITLE
Consecration

### ISSUE THREAD

**Issue by RaphaelPage0110** [RaphaelPage0110/mini-hearthStone#3]
Est-ce que la consecration fait des dégats seulement aux serviteurs ou également au héros adverse?

**Comment by GlennPlou** [comment]
![image](https://user-images.githubusercontent.com/33932970/49044453-1a346b00-f1ce-11e8-84b2-63f0c6c6acc5.png)
Ça rage dans les commentaires, donc apparemment ca touche les serviteurs ennemis + le héros adverse.

**Comment by RaphaelPage0110** [comment]
Ahaha on part sur une consécration qui touche le Hero aussi alors 😂😂
