### ISSUE TITLE
Code smells

### ISSUE THREAD

**Issue by GlennPlou** [RaphaelPage0110/mini-hearthStone#8]
Les classes DamageAllMinions, DamageAllOpponents,DamageEnemyMinions,DamageTarget font la même chose, seul la cible est modifiée.

Idée : modifier l'interface CardAction, notamment la méthode `effect(Target myTarget);` qui deviendrait alors : 

`effect(ArrayList<Target> myTargets);`

**Comment by GlennPlou** [comment]
Ca me chiffonne un peu cette histoire puisque du coup où est-ce qu'on va définir quelles cibles doit atteindre l'effet spécial en question ? Ca devrait être géré par un attribut dans la base de données qui nous indique la liste des cibles à atteindre... Du coup faudrait se mettre d'accord sur une syntaxe à gérer, ca me parait trop compliqué cette histoire.

**Comment by RaphaelPage0110** [comment]
Je pense pas que ce soit possible de stocker en bdd la liste des cibles d'un sort ^^ Ca change à chaque fois!
Je pense qu'on s'occupera ca dans la partie de code qui gère la partie. Je vois un truc du genre:

- le client envoie une information au serveur qu'il veut invoquer un serviteur;

- le serveur lui renvoie "ok poto t'as assez de mana pour l'invoquer. Il a un effet qui buff une autre de tes cartes. Tu veux que ce soit qui?";

- du coup le joueur lui dit "groooos le sanglier!";

- et le serveur : "oki ton sanglier est hyper fort maintenant! tmtc!"

Ou un truc dans le genre?

**Comment by GlennPlou** [comment]
Aucune idée, on demandera l'avis à El Profesor demain je pense
