### ISSUE TITLE
Appliquer la classe CardAction pour les héros

### ISSUE THREAD

**Issue by GlennPlou** [RaphaelPage0110/mini-hearthStone#9]
Les héros ont aussi des actions spéciales qui correspondent aux comportements déjà implémentés. Je propose de renommer la classe `CardAction` en `Effect`. 
Card aura donc un attribut `protected ArrayList<Effect> myEffects;` (ce qui est déjà le cas)
Et Héros aussi se verra attribuer un attribut du même genre.

**Comment by RaphaelPage0110** [comment]
Yes, j'aime!

**Comment by RaphaelPage0110** [comment]
J'ai appliqué cette idée dans le commit 3ac92e1
